services:
  app:
    build: .
    container_name: matrix-render-engine
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    ports:
      - 8080:80
      - 5678:5678
    volumes:
      - .:/app
    env_file:
      - .env